# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Synerminds Blog
email: info@synerminds.com
description: >
  This is the place where we share with the community our lessons learned
  while working on products or prototypes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://synerminds.com" # the base hostname & protocol for your site
twitter_username:
github_username:  synerminds
repository: https://github.com/synerminds/synerminds.github.io

# Build settings
markdown: kramdown
